import './sass/main.scss';
import './js/get-genres';
import './js/renderTrendingMovies.js';
import './js/renderMovieForQuery.js';
import './js/pagination';
import { onHomeClick, onLibraryClick } from './js/header-logic';
import './js/modal-card';
import './js/thems';
import './js/toTop';
import './js/modal-team';
